### ISSUE TITLE
doesn't work (guardian patch)

### ISSUE THREAD

**Issue by lidel97** [Owyn/lockons-light#2]
i installed the module, it's correctly initialized but it doesn't work, in the read me guide there are no commands to type on the proxy chat, i already tried the command used for autolockon master but i have "unknown command". can you help me? thanx

**Comment by Owyn** [comment]
I'm pretty sure you're just expecting it to do what it's not supposed to do.

Try re-reading the description, it's full and correct about what the module does.

**Comment by lidel97** [comment]
so basically, it doesn't work like the autolock on module but i have to lock manually the target i want , is it correct what i've written?

**Comment by Owyn** [comment]
module doesn't do anything with how you lock
